### PR TITLE
fix #51: shadow elm-compile-arguments with output

### LINKED ISSUE #51: elm-compile-buffer with output argument fails
Problem seems to be in how the argument list is modified in `elm-compile--command`. Compile output below. PR forthcoming.

```
elm-make HelloWorld.elm --output=~/gdrive/src/elm_by_example/HelloWorld.html --yes --warn --output=elm.js
elm-make 0.16 (Elm Platform 0.16.0)

Usage: elm-make [FILES...] [--output FILE] [--yes] [--report FORMAT] [--warn]
                [--docs FILE]
  build Elm projects

Available options:
  -h,--help                Show this help text
  --output FILE            Write result to the given .html or .js FILE.
  --yes                    Reply 'yes' to all automated prompts.
  --report FORMAT          Format of error and warning reports (e.g.
                           --report=json)
  --warn                   Report warnings to improve code quality.
  --docs FILE              Write documentation to FILE as JSON.

Examples:
  elm-make Main.elm                     # compile to HTML in index.html
  elm-make Main.elm --output main.html  # compile to HTML in main.html
  elm-make Main.elm --output elm.js     # compile to JS in elm.js
  elm-make Main.elm --warn              # compile and report warnings

Full guide to using elm-make at <https://github.com/elm-lang/elm-make>

Compilation exited abnormally with code 1 at Wed Dec 23 22:31:10
```

### PR DESCRIPTION
**Pull request by wobh**
This should do it.

### CODE REVIEW

**Comment by wobh** [comment]
It's sort of a matter of personal style but I'm fine with doing `setf` on the shadowed `elm-compile-arguments` like this:

```lisp
  (let ((elm-compile-arguments elm-compile-arguments))
    (when output
      (setf elm-compile-arguments
            (append (butlast elm-compile-arguments)
                    (list (concat " --output=" (expand-file-name output))))))
    (mapconcat 'identity
               (append (list elm-compile-command file) elm-compile-arguments)
               " "))
```

If you prefer something that or any other concern, let me know.

**Comment by wobh** [comment]
I didn't notice you were using `cl-lib` Seems like I could simplify the command list generation with `cl-list*`.

**Comment by Bogdanp** [comment]
Thanks for contributing! I think `(butlast elm-compile-arguments)` should be replaced w/ something like `(cl-remove-if (apply-partially #'string-prefix-p "--output=") elm-compile-arguments)`. Looks good otherwise!

**Comment by wobh** [comment]
I think if the compile command line were much more complex and order independent access to the options were desired, it would be worth considering using struct and an API sort of like Emac's `url`. Something like that might be useful even now since there's multiple command lines to build (I'm not yet sure if there's a similar bug in `elm-package`). I'm going through a tutorial right now and really digging Elm so far, so thank you for your work on this, and if there's anything I can do to pitch in, let me know!

**Pull request merged**
